name: build
on: [push, pull_request]

jobs:
  ubuntu_native_hosted:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Dependencies
        run: |
          git clone --depth=1 https://github.com/microsoft/vcpkg /tmp/vcpkg
          cd $_
          VCPKG_DISABLE_METRICS=1 ./bootstrap-vcpkg.sh
          ./vcpkg install openssl zlib
        shell: bash
      - name: Build
        run: |
          mkdir build && cd $_
          cmake -DCMAKE_BUILD_TYPE="Debug" \
                -DCMAKE_TOOLCHAIN_FILE="/tmp/vcpkg/scripts/buildsystems/vcpkg.cmake" \
                ..
          cmake --version
          which cmake
          cmake --build \
                .
        shell: bash
