name: build
on: [push, pull_request]

jobs:
  ubuntu_native_hosted:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Dependencies
        run: |
          git clone --depth=1 https://github.com/microsoft/vcpkg /tmp/vcpkg
          cd $_
          ./bootstrap-vcpkg.sh
          ./vcpkg install openssl:linux-x64 zlib:linux-x64
        shell: bash
      - name: Build
        run: |
          mkdir build && cd $_
          cmake .. \
                -DCMAKE_BUILD_TYPE="Debug" \
                -DCMAKE_TOOLCHAIN_FILE="/tmp/vcpkg/scripts/buildsystems/vcpkg.cmake"
          cmake . --build
        shell: bash
